### ISSUE TITLE
编译example_fish_protocol过程中出现下面错误该怎么解决啊

### ISSUE THREAD

**Issue by YuanpengDuan** [fishros/fish_protocol#2]
Starting >>> example_fish_protocol
--- stderr: example_fish_protocol                              
/usr/bin/ld: CMakeFiles/example_fish_protocol.dir/src/example_fish_protocol.cpp.o: undefined reference to symbol '_ZN5boost6system15system_categoryEv'
//usr/lib/x86_64-linux-gnu/libboost_system.so.1.65.1: 无法添加符号: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [example_fish_protocol] Error 1
make[1]: *** [CMakeFiles/example_fish_protocol.dir/all] Error 2
make: *** [all] Error 2

Failed   <<< example_fish_protocol [3.46s, exited with code 2]

Summary: 0 packages finished [3.63s]
  1 package failed: example_fish_protocol
  1 package had stderr output: example_fish_protocol

**Comment by fishros** [comment]
这里有做吗,你的系统中boost是哪一个版本
```
sudo apt install libboost-dev
git clone https://gh.api.99988866.xyz/https://github.com/fishros/fish_protocol.git 
cd fish_protocol && mkdir build  && cd build
cmake .. && sudo make install # 将安装到系统库
```

**Comment by YuanpengDuan** [comment]
我做过了，boost版本为1.65

**Comment by YuanpengDuan** [comment]
解决了，先通过`locate  boost_system`查找boost库，然后将找到的路径添加到`CMakeLists.txt`
```bash
target_link_libraries(example_fish_protocol
  "fish_protocol"
  /usr/lib/x86_64-linux-gnu/libboost_system.a
  /usr/lib/x86_64-linux-gnu/libboost_system.so
  /usr/lib/x86_64-linux-gnu/libboost_system.so.1.65.1
)
```
